export interface Product {
  id: string;
  name: string;
  slug: string;
  description: string;
  price: number;
  compareAtPrice?: number;
  category: string;
  categorySlug: string;
  stock: number;
  type: 'physical' | 'digital';
  rating: number;
  reviewCount: number;
  images: string[];
  tags: string[];
  featured: boolean;
  discount?: number;
}

export const featuredProducts: Product[] = [
  {
    id: '1',
    name: 'Notebook Gamer Pro',
    slug: 'notebook-gamer-pro',
    description: 'Notebook de alta performance',
    price: 5499.99,
    compareAtPrice: 6999.99,
    images: ['/products/notebook-1.jpg'],
    category: 'Eletrônicos',
    categorySlug: 'eletronicos',
    stock: 15,
    type: 'physical',
    rating: 4.8,
    reviewCount: 342,
    tags: ['notebook', 'gamer'],
    featured: true,
    discount: 21,
  },
  {
    id: '2',
    name: 'Mouse Gamer RGB',
    slug: 'mouse-gamer-rgb',
    description: 'Mouse gamer 7 botões',
    price: 149.90,
    compareAtPrice: 249.90,
    images: ['/products/mouse-1.jpg'],
    category: 'Eletrônicos',
    categorySlug: 'eletronicos',
    stock: 87,
    type: 'physical',
    rating: 4.6,
    reviewCount: 156,
    tags: ['mouse', 'gamer'],
    featured: true,
    discount: 40,
  },
  {
    id: '3',
    name: 'Teclado Mecânico RGB',
    slug: 'teclado-mecanico-rgb',
    description: 'Teclado mecânico switches blue',
    price: 399.90,
    compareAtPrice: 599.90,
    images: ['/products/keyboard-1.jpg'],
    category: 'Eletrônicos',
    categorySlug: 'eletronicos',
    stock: 42,
    type: 'physical',
    rating: 4.9,
    reviewCount: 289,
    tags: ['teclado'],
    featured: true,
    discount: 33,
  },
  {
    id: '4',
    name: 'Headset Gamer 7.1',
    slug: 'headset-gamer',
    description: 'Headset surround 7.1',
    price: 279.90,
    images: ['/products/headset-1.jpg'],
    category: 'Eletrônicos',
    categorySlug: 'eletronicos',
    stock: 63,
    type: 'physical',
    rating: 4.5,
    reviewCount: 178,
    tags: ['headset'],
    featured: true,
  },
  {
    id: '5',
    name: 'Webcam Full HD',
    slug: 'webcam-full-hd',
    description: 'Webcam 1080p',
    price: 189.90,
    compareAtPrice: 299.90,
    images: ['/products/webcam-1.jpg'],
    category: 'Eletrônicos',
    categorySlug: 'eletronicos',
    stock: 28,
    type: 'physical',
    rating: 4.4,
    reviewCount: 94,
    tags: ['webcam'],
    featured: true,
    discount: 37,
  },
  {
    id: '6',
    name: 'PlayStation 5 Digital',
    slug: 'playstation-5-digital',
    description: 'Console PS5 Edição Digital',
    price: 3499.90,
    compareAtPrice: 3999.90,
    images: ['/products/ps5.jpg'],
    category: 'Consoles',
    categorySlug: 'consoles',
    stock: 12,
    type: 'physical',
    rating: 5.0,
    reviewCount: 523,
    tags: ['playstation', 'console', 'games'],
    featured: true,
    discount: 13,
  },
  {
    id: '7',
    name: 'Xbox Series S',
    slug: 'xbox-series-s',
    description: 'Console Xbox Series S 512GB',
    price: 2299.90,
    compareAtPrice: 2799.90,
    images: ['/products/xbox.jpg'],
    category: 'Consoles',
    categorySlug: 'consoles',
    stock: 18,
    type: 'physical',
    rating: 4.7,
    reviewCount: 412,
    tags: ['xbox', 'console', 'games'],
    featured: true,
    discount: 18,
  },
  {
    id: '8',
    name: 'Monitor Gamer 144Hz',
    slug: 'monitor-gamer-144hz',
    description: 'Monitor 27" Full HD 144Hz 1ms',
    price: 1299.90,
    compareAtPrice: 1899.90,
    images: ['/products/monitor.jpg'],
    category: 'Eletrônicos',
    categorySlug: 'eletronicos',
    stock: 24,
    type: 'physical',
    rating: 4.8,
    reviewCount: 267,
    tags: ['monitor', 'gamer', '144hz'],
    featured: true,
    discount: 32,
  },
  {
    id: '9',
    name: 'SSD NVMe 1TB',
    slug: 'ssd-nvme-1tb',
    description: 'SSD M.2 NVMe PCIe 4.0 1TB',
    price: 499.90,
    compareAtPrice: 799.90,
    images: ['/products/ssd.jpg'],
    category: 'Hardware',
    categorySlug: 'hardware',
    stock: 56,
    type: 'physical',
    rating: 4.9,
    reviewCount: 189,
    tags: ['ssd', 'storage', 'hardware'],
    featured: true,
    discount: 38,
  },
  {
    id: '10',
    name: 'Cadeira Gamer RGB',
    slug: 'cadeira-gamer-rgb',
    description: 'Cadeira Gamer Ergonômica com LED RGB',
    price: 899.90,
    compareAtPrice: 1299.90,
    images: ['/products/cadeira.jpg'],
    category: 'Acessórios',
    categorySlug: 'acessorios',
    stock: 15,
    type: 'physical',
    rating: 4.6,
    reviewCount: 145,
    tags: ['cadeira', 'gamer', 'setup'],
    featured: true,
    discount: 31,
  },
  {
    id: '11',
    name: 'Placa de Vídeo RTX 4060',
    slug: 'rtx-4060',
    description: 'NVIDIA GeForce RTX 4060 8GB',
    price: 2199.90,
    compareAtPrice: 2799.90,
    images: ['/products/gpu.jpg'],
    category: 'Hardware',
    categorySlug: 'hardware',
    stock: 8,
    type: 'physical',
    rating: 5.0,
    reviewCount: 456,
    tags: ['gpu', 'nvidia', 'rtx'],
    featured: true,
    discount: 21,
  },
  {
    id: '12',
    name: 'Controle Xbox Wireless',
    slug: 'controle-xbox-wireless',
    description: 'Controle Xbox Sem Fio - Edição Carbon',
    price: 399.90,
    compareAtPrice: 549.90,
    images: ['/products/controle.jpg'],
    category: 'Acessórios',
    categorySlug: 'acessorios',
    stock: 34,
    type: 'physical',
    rating: 4.7,
    reviewCount: 278,
    tags: ['controle', 'xbox', 'wireless'],
    featured: true,
    discount: 27,
  },
];
